[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build -- --configuration=production"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Configuration spécifique pour le frontend Angular
# Railway détectera automatiquement npm via package.json