version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: pmt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pmt_db
      MYSQL_USER: pmt_user
      MYSQL_PASSWORD: pmt_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  # Backend Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pmt-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pmt_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: pmt_user
      SPRING_DATASOURCE_PASSWORD: pmt_password
      JWT_SECRET: yourVerySecretKeyThatIsAtLeast256BitsLongAndShouldBeStoredSecurely
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - pmt-network

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pmt-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - pmt-network

volumes:
  mysql_data:

networks:
  pmt-network:
    driver: bridge