[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Configuration spécifique pour le backend Spring Boot
# Railway détectera automatiquement Maven via pom.xml
